source /opt/ros/${ROS_DISTRO}/setup.bash

source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
source /usr/share/colcon_cd/function/colcon_cd.sh

export GAZEBO_MODEL_PATH=/usr/share/gazebo-11/models
export GAZEBO_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/gazebo-11/plugins